import { StyleSheet } from "react-native";
import {COLORS,SIZES} from '../constants'

const styles = StyleSheet.create({
    container:{
        flex:1,
        color:COLORS.lightWhite
    },
    upperRow:{
        marginHorizontal:20,
        marginTop:-30,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        position:'absolute',
        top:SIZES.xxLarge,
        width:SIZES.width-44,
        zIndex:999

    },
    image:{
        aspectRatio:1,
        resizeMode:'cover'
    },
    details:{
        marginTop:-SIZES.large,
        backgroundColor:COLORS.lightWhite,
        width:SIZES.width,
        borderTopLeftRadius:SIZES.medium,
        borderTopRightRadius:SIZES.medium
    },
    titleRow:{
        marginHorizontal:10,
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width-20,
        top:10
    },
    ratingRow:{
        marginHorizontal:10,
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width-20,
        top:5
    },
    rating:{
        top:SIZES.large - 12,
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
    },
    title:{
        fontFamily:'bold',
        fontSize:SIZES.large
    },
    priceWrapper:{
        backgroundColor:COLORS.secondary,
        borderRadius:SIZES.large
    },
    price:{
        paddingHorizontal:10,
        fontFamily:'semibold',
        fontSize:SIZES.large
    },
    ratingText:{
        color:COLORS.gray,
        fontFamily:"medium",
        marginHorizontal:3,
        paddingHorizontal:5
    },
    descriptionWrapper:{
        marginTop:SIZES.large*2-20,
        marginHorizontal:SIZES.large,
        marginBottom:-25
    },
    description:{
        fontFamily:"medium",
        fontSize:SIZES.large-2,
    },
    descText:{
        fontFamily:'regular',
        fontSize:SIZES.small,
        textAlign:'justify',
        marginBottom:SIZES.small
    },
    location:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:COLORS.secondary,
        padding:5,
        borderRadius:SIZES.large,
    }
})

export default styles;