import { StyleSheet } from "react-native";
import {COLORS,SIZES} from '../constants'
import { Colors } from "react-native/Libraries/NewAppScreen";

const styles = StyleSheet.create({
    container:{
        flex:1,
        color:COLORS.lightWhite
    },
    upperRow:{
        marginHorizontal:20,
        marginTop:-30,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        position:'absolute',
        top:SIZES.xxLarge,
        width:SIZES.width-44,
        zIndex:999

    },
    image:{
        aspectRatio:1,
        resizeMode:'cover'
    },
    details:{
        marginTop:-SIZES.xxLarge + 5,
        backgroundColor:COLORS.lightWhite,
        width:SIZES.width,
        borderTopLeftRadius:SIZES.medium,
        borderTopRightRadius:SIZES.medium
    },
    titleRow:{
        marginHorizontal:20,
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width-44,
        top:20
    },
    ratingRow:{
        marginHorizontal:10,
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width-20,
        top:5
    },
    rating:{
        top:SIZES.large - 12,
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
    },
    title:{
        fontFamily:'bold',
        fontSize:SIZES.large
    },
    priceWrapper:{
        backgroundColor:COLORS.secondary,
        borderRadius:SIZES.large
    },
    price:{
        paddingHorizontal:10,
        fontFamily:'semibold',
        fontSize:SIZES.large
    },
    ratingText:{
        color:COLORS.gray,
        fontFamily:"medium",
        marginHorizontal:3,
        paddingHorizontal:SIZES.xSmall
    },
    descriptionWrapper:{
        marginTop:SIZES.large*2-40,
        marginHorizontal:SIZES.large,
        marginBottom:-25
    },
    description:{
        fontFamily:"medium",
        fontSize:SIZES.large-2,
    },
    descText:{
        fontFamily:'regular',
        fontSize:SIZES.small,
        textAlign:'justify',
        marginBottom:SIZES.small
    },
    location:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:COLORS.secondary,
        padding:5,
        borderRadius:SIZES.large,
        marginHorizontal:SIZES.large - 4,
        marginVertical:20
    },
    cartRow:{
        paddingBottom:SIZES.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZES.width,
        marginHorizontal:SIZES.large - 20,
        marginVertical:-25
    },
    cartBtn:{
        width:SIZES.width*0.7,
        backgroundColor:COLORS.black,
        padding:SIZES.small/2,
        borderRadius:SIZES.large,
        marginLeft:12
    },
    cartTitle:{
        marginLeft:SIZES.small,
        fontFamily:'bold',
        fontSize:SIZES.medium,
        color:COLORS.lightWhite
    },
    addCart:{
        width:37,
        height:37,
        borderRadius:50,
        margin:SIZES.small,
        backgroundColor:COLORS.black,
        alignItems:'center',
        justifyContent:'center'
    }
})

export default styles;